swagger: '2.0'
info:
  title: User API
  version: 1.0.0
basePath: /user
tags:
  - name: Users
    description: Operations related to users
paths:
  /user/login:
    post:
      tags:
        - Users
      summary: Log in an existing user
      parameters:
        - name: body
          in: body
          description: User object containing email and password
          required: true
          schema:
            $ref: '#/definitions/UserLoginInput'
      responses:
        200:
          description: Successful operation
          schema:
            $ref: '#/definitions/UserLoginResponse'
  /user/register:
    post:
      tags:
        - Users
      summary: Register a new user
      parameters:
        - name: body
          in: body
          description: User object containing email, username, and password
          required: true
          schema:
            $ref: '#/definitions/UserRegisterInput'
      responses:
        200:
          description: Successful operation
          schema:
            $ref: '#/definitions/UserResponse'

definitions:
  UserLoginInput:
    type: object
    properties:
      email:
        type: string
      password:
        type: string
    required:
      - email
      - password

  UserRegisterInput:
    type: object
    properties:
      email:
        type: string
      username:
        type: string
      password:
        type: string
    required:
      - email
      - username
      - password

  UserResponse:
    type: object
    properties:
      success:
        type: boolean
        default: true
      user:
        $ref: '#/definitions/User'

  UserLoginResponse:
    type: object
    properties:
      success:
        type: boolean
        default: true
      token:
        type: string
      user:
        $ref: '#/definitions/User'

  User:
    type: object
    properties:
      id:
        type: integer
      email:
        type: string
      username:
        type: string
